### PR TITLE
Clean package names.

### PR DESCRIPTION
**Pull request by angelozerr**
Clean package names.

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
This PR group features in a proper package name. It follows the same package names than other internal lemminx extension (with participants package name).

**Comment by mickaelistria** [comment]
Seems like Snippets are broken by that change. Feel free to just remove anything snippet related by the way, we don't really need them IMO.

**Comment by angelozerr** [comment]
> Seems like Snippets are broken by that change. Feel free to just remove anything snippet related by the way, we don't really need them IMO.

I removed it, but I would like to keep it since vscode-maven provides this kind of snippet. I will create an another PR for that to support this snippet but with the LemMinx snippet support which is more robust.

**Comment by mickaelistria** [comment]
Thanks!

**Pull request merged**
