### PR TITLE
Maven Resolver 1.9.0

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by mickaelistria** [comment]
@akurtakov I don't remember what's the trick to get automatic CQ creation from GitHub? Is there some bot to enable or a magic request to use in comment?

**Comment by akurtakov** [comment]
> /request-license-review

This is the magic but the comment has to be created by committer for dependabot to act.

**Comment by akurtakov** [comment]
@HannesWell can you help what we miss here for the request-license-review to work?

**Comment by vrubezhny** [comment]
Just note that two (out of 5) IPTeam requests were created by dependabot:

- [maven/mavencentral/org.apache.maven.resolver/maven-resolver-api/1.9.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/4954)
- [maven/mavencentral/org.apache.maven.resolver/maven-resolver-util/1.9.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/4953) 
 
 The requests for the other three dependencies were lost somewhere... maybe there is some limit preventing the dependabot from openning "too many IPTeam requests at once"-like (similar to `open-pull-requests-limit`)?

**Comment by mickaelistria** [comment]
Those 2 requests come from Tycho. The lemminx-maven /request-license-review didn't manage to open new requests. Should we setup some secret or permissions?

**Comment by HannesWell** [comment]
> Those 2 requests come from Tycho. The lemminx-maven /request-license-review didn't manage to open new requests. Should we setup some secret or permissions?

Yes you need an IPLab authentication token stored in this GH repos secret store (since the orga is quite large you probably don't want it for that).

See for example how it was done for the Platform-Releng repo:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1464

The request is quite complete. The only additional step that was missing was to confirm the bot's email address as I asked in the comments.

**Comment by HannesWell** [comment]
> @akurtakov I don't remember what's the trick to get automatic CQ creation from GitHub? Is there some bot to enable or a magic request to use in comment?

At the very end of the license-check workflow the instructions are mentioned:
`Committers can request a review by commenting '/request-license-review'`

It would be indeed nicer to see that somehow in the status but I don't know how to do that.

**Comment by mickaelistria** [comment]
OK, I opened request to Eclipse infra team to add secret: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2258

**Comment by vrubezhny** [comment]
> Those 2 requests come from Tycho. The lemminx-maven /request-license-review didn't manage to open new requests.

Ah. Yes. That's true

**Comment by mickaelistria** [comment]
Thanks @vrubezhny for opening the IP requests!

**Pull request merged**
