### PR TITLE
Switch to use OkHttpClient instead of Unirest-Java

### PR DESCRIPTION
**Pull request by vrubezhny**
Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
I merged a patch removing usage of indexer class, it basically replace usage of ArtifactInfo by org.apache.maven.aether.Artifact. Please try rebasing, hopefully merge is simple.
Also, please remove the various System.err.println. If they're often useful, you may want to use `LOGGER.finest(...)` to log those, and configure the tests so the the "finest" level is enabled.

**Comment by vrubezhny** [comment]
@mickaelistria Done.

**Comment by fbricon** [comment]
Why not use java 11's built-in http client?

**Comment by mickaelistria** [comment]
> Why not use java 11's built-in http client?

That would be a good improvement; but as okhttp3 is there and loaded anyway when trying to fetch artifacts, I don't think there would be much immediate win. But indeed, we'll need to get rid of okhttp3 if Maven itself stops using it.

**Pull request merged**
