### PR TITLE
Add system properties to ProjectBuildRequest

### PR DESCRIPTION
**Pull request by mickaelistria**
That allows to properly resolve profiles and other stuff relying on
system properties.

Signed-off-by: Mickael Istria <mistria@redhat.com>

### CODE REVIEW

**Comment by PyvesB** [comment]
Thanks for picking this up. Out of interest, how do system properties related to BOM dependencies?

**Comment by mickaelistria** [comment]
When writing the test case, I saw there were actually 2 errors, one being about "Failed to determine Java version for profile...". So I looked for this message in Maven code base (I have it locally, it's pretty useful to have it here when working on LemMinX-Maven or Maven) and found it's happening when the "java.version" system property isn't available in the projectBuildingRequest. So I just forwarding existing properties and saw the test pass.

**Comment by AObuchow** [comment]
Although I dislike having to add software.amazon.awssdk:bom as a dependency to the build just for test's, it's the current state of lemminx-maven so I'll deal with it ;) This week I intend to look into maven dependency & plugin downloading so that Lemminx-Maven can download pom dependencies if they don't exist locally. Hopefully, that will remove the need for this new dependency.

**Comment by AObuchow** [comment]
Other than that, looks good to me. Glad to see the fix was relatively simple. Great patch @mickaelistria !

**Pull request merged**
