### PR TITLE
Mickaelistria repo local

### PR DESCRIPTION
**Pull request by AObuchow**
This is just to test Mickael's patch on CI

### CODE REVIEW

**Comment by AObuchow** [comment]
20 out of 25 of the tests had errors:
```
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   LocalRepoTests.testCompleteDependency:55 » TestTimedOut test timed out after 9...
[ERROR]   LocalRepoTests.testCompleteLocalGroupdId:71 » TestTimedOut test timed out afte...
[ERROR]   PluginTest.testCompleteConfigurationParameters:82 » TestTimedOut test timed ou...
[ERROR]   PluginTest.testCompleteConfigurationParametersInTag:97 » TestTimedOut test tim...
[ERROR]   PluginTest.testCompleteGoal:66 » TestTimedOut test timed out after 15000 milli...
[ERROR]   PluginTest.testPluginArtifactHover:132 » TestTimedOut test timed out after 150...
[ERROR]   PluginTest.testPluginConfigurationHover:111 NullPointer
[ERROR]   PluginTest.testPluginGoalHover:120 » TestTimedOut test timed out after 15000 m...
[ERROR]   RemoteRepositoryTest.testRemoteArtifactHover:102 » TestTimedOut test timed out...
[ERROR]   RemoteRepositoryTest.testRemoteArtifactIdCompletion:74 » TestTimedOut test tim...
[ERROR]   RemoteRepositoryTest.testRemoteGroupIdCompletion:60 » TestTimedOut test timed ...
[ERROR]   RemoteRepositoryTest.testRemotePluginArtifactIdCompletion:130 » TestTimedOut t...
[ERROR]   RemoteRepositoryTest.testRemotePluginGroupIdCompletion:116 » TestTimedOut test...
[ERROR]   RemoteRepositoryTest.testRemotePluginVersionCompletion:144 » TestTimedOut test...
[ERROR]   RemoteRepositoryTest.testRemoteVersionCompletion:88 » TestTimedOut test timed ...
[ERROR]   SimpleModelTest.testCompletePhase:193 » TestTimedOut test timed out after 1500...
[ERROR]   SimpleModelTest.testCompleteScope:168 » TestTimedOut test timed out after 1500...
[ERROR]   SimpleModelTest.testLocalParentGAVCompletion:113 » TestTimedOut test timed out...
[ERROR]   SimpleModelTest.testMissingArtifactIdError:147 » TestTimedOut test timed out a...
[ERROR]   SimpleModelTest.testPropertyHover:211 » TestTimedOut test timed out after 1500...
```

Some of these are expected to fail:
- The plugin related tests, as we haven't implemented a way for a plugin to be downloaded if it doesn't exist in the local repository, including:
    - `PluginTest.testPluginGoalHover`
    - `PluginTest.testPluginConfigurationHover`
    - `PluginTest.testPluginArtifactHover`
    - `PluginTest.testCompleteGoal`
    - `PluginTest.testCompleteConfigurationParametersInTag`
    - `PluginTest.testCompleteConfigurationParameters`
- Local repo tests (I believe?) for the same reason as plugin tests - if the dependency isin't present on CI, it'll fail
    - `LocalRepoTests.testCompleteDependency`
    - `LocalRepoTests.testCompleteLocalGroupdId`

**Comment by mickaelistria** [comment]
The point with setting the same maven.repo.local for build and tests is actually to make the local tests pass as well as both would share the same local repo.

**Comment by AObuchow** [comment]
> The point with setting the same maven.repo.local for build and tests is actually to make the local tests pass as well as both would share the same local repo.

Ok I see

**Comment by mickaelistria** [comment]
I think the main issue is

```
Could not transfer artifact org.apache.maven.plugins:maven-dependency-plugin:pom:3.1.1 from/to central (default): Cannot access default with type default using the available connector factories: BasicRepositoryConnectorFactory
[...]
Caused by: org.eclipse.aether.transfer.NoTransporterException: No transporter factories registered
```

It looks like we miss a dependency in the tests, maybe something like aether-transport-http.
However, I don't get why this cannot be reproduced locally...

**Comment by AObuchow** [comment]
> I think the main issue is
> 
> 
> 
> ```
> 
> Could not transfer artifact org.apache.maven.plugins:maven-dependency-plugin:pom:3.1.1 from/to central (default): Cannot access default with type default using the available connector factories: BasicRepositoryConnectorFactory
> 
> [...]
> 
> Caused by: org.eclipse.aether.transfer.NoTransporterException: No transporter factories registered
> 
> ```
> 
> 
> 
> It looks like we miss a dependency in the tests, maybe something like aether-transport-http.
> 
> However, I don't get why this cannot be reproduced locally...

IIRC that error occurs when you try to resolve a maven plugin that doesn’t exist in the local .m2 folder. 

To verify this, you can either:
- Delete maven-dependency-plugin 3.1.1 from your local .m2/repository folder
- Change the version of maven-dependency-plugin to test for (eg. 9.9.9) so that you won’t have the version locally 

If you’re able to reproduce the error with the steps above, then this confirms that we need to add support for downloading maven-plugins if they don’t exist locally (for better UX & for tests to fully pass).

**Comment by mickaelistria** [comment]
I'm not sure it's related to the local repo.
From this PR head commit 4f8c3e7 , I tried `mvn clean verify -Dmaven.repo.local=$(pwd)/target/test-repo` where the repo doesn't pre-exist, and got a relative success without such errors
```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   PluginTest.testPluginArtifactHover:134
[ERROR] Errors: 
[ERROR]   RemoteRepositoryTest.testRemoteArtifactHover:102 » TestTimedOut test timed out...
[INFO] 
[ERROR] Tests run: 25, Failures: 1, Errors: 1, Skipped: 0
```
without a note about transport errors.

**Comment by AObuchow** [comment]
> I'm not sure it's related to the local repo.
> From this PR head commit [4f8c3e7](https://github.com/eclipse/lemminx-maven/commit/4f8c3e7f1dd750327f35ac68e676075420a9eb82) , I tried `mvn clean verify -Dmaven.repo.local=$(pwd)/target/test-repo` where the repo doesn't pre-exist, and got a relative success without such errors without a note about transport errors.

When trying to reproduce it, I got a similar (but more longer) stacktrace:
```
org.apache.maven.plugin.PluginResolutionException: Plugin org.apache.maven.plugins:maven-dependency-plugin:9.9.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-dependency-plugin:jar:9.9.1
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:120)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getPluginDescriptor(DefaultMavenPluginManager.java:182)
	at org.eclipse.lemminx.maven.MavenPluginUtils.getContainingPluginDescriptor(MavenPluginUtils.java:101)
	at org.eclipse.lemminx.maven.MavenHoverParticipant.collectGoal(MavenHoverParticipant.java:132)
	at org.eclipse.lemminx.maven.MavenHoverParticipant.onText(MavenHoverParticipant.java:180)
	at org.eclipse.lemminx.services.XMLHover.getTextHover(XMLHover.java:107)
	at org.eclipse.lemminx.services.XMLHover.doHover(XMLHover.java:94)
	at org.eclipse.lemminx.services.XMLLanguageService.doHover(XMLLanguageService.java:147)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$hover$2(XMLTextDocumentService.java:186)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.apache.maven.plugins:maven-dependency-plugin:jar:9.9.1
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:255)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:255)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:106)
	... 16 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.apache.maven.plugins:maven-dependency-plugin:pom:9.9.1 from/to central (default): Cannot access default with type default using the available connector factories: BasicRepositoryConnectorFactory <------------------------------------------------------------
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:424)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240)
	... 19 more
```

**Comment by mickaelistria** [comment]
I think the maven.repo.local property is ignored because local settings take precedence. I'm trying some other stuff to workaround this issue.

**Comment by AObuchow** [comment]
> I think the maven.repo.local property is ignored because local settings take precedence. I'm trying some other stuff to workaround this issue.

Okay sounds good. Let me know if you need me to change anything on the Jenkins CI side/configuration

**Comment by mickaelistria** [comment]
Replaced by #31, feel free to close.

**Pull request closed without merging**
