### PR TITLE
Support InsertTextMode client capability for completion

### LINKED ISSUE #469: Completion apply generate bad indentation in vscode
See below demo:

LemminxMavenCompletionInVScode

This problem doesn't occur inEclipse IDE, because it doesn't support `InsertTextMode.AdjustIndentation`, vscode supports it so the lemminx maven should not indent when the LSP client has this capability.

//cc @rgrunber

### PR DESCRIPTION
**Pull request by JessicaJHee**
Fixes #469 

Peek 2023-08-01 16-46

### CODE REVIEW

**Comment by angelozerr** [comment]
The PR looksgood but CI build is falling https://github.com/eclipse/lemminx-maven/actions/runs/5731748454/job/15533309939?pr=482#step:4:24748

I suspect there is a NPE here https://github.com/eclipse/lemminx-maven/pull/482/files#diff-fd5fcfd611c837cfbfeeb50a4f824ca8135c4f0367a900d1f362a67d0e9df1ebR1299 but not sure with that

**Comment by JessicaJHee** [comment]
@angelozerr yes I need to update the test settings, will mark this PR as ready once that's done :+1:

**Comment by angelozerr** [comment]
@vrubezhny could you check that this PR doesn't break Eclipse IDE completion please

**Comment by vrubezhny** [comment]
One of the Exceptions, for sure, prevents completion items to be created:
```
Aug 01, 2023 8:59:55 PM org.eclipse.lemminx.services.XMLCompletions collectInsideContent
SEVERE: While performing ICompletionParticipant#onXMLContent for participant 'org.eclipse.lemminx.extensions.maven.participants.completion.MavenCompletionParticipant'.
java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4j.CompletionCapabilities.getInsertTextMode()" because the return value of "org.eclipse.lemminx.settings.XMLCompletionSettings.getCompletionCapabilities()" is null
	at org.eclipse.lemminx.extensions.maven.participants.completion.MavenCompletionParticipant.getInsertTextMode(MavenCompletionParticipant.java:1299)
	at org.eclipse.lemminx.extensions.maven.participants.completion.MavenCompletionParticipant.toGAVCompletionItem(MavenCompletionParticipant.java:779)
	at org.eclipse.lemminx.extensions.maven.participants.completion.MavenCompletionParticipant.lambda$onXMLContent$37(MavenCompletionParticipant.java:485)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.eclipse.lemminx.extensions.maven.participants.completion.MavenCompletionParticipant.onXMLContent(MavenCompletionParticipant.java:487)
	at org.eclipse.lemminx.services.XMLCompletions.collectInsideContent(XMLCompletions.java:798)
	at org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:260)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:171)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:166)
	at org.eclipse.lemminx.extensions.maven.participants.LocalRepoTests.testCompleteDependency(LocalRepoTests.java:52)
```

**Comment by angelozerr** [comment]
I tested in Eclipse IDE to check it doesn't break something and in vscode and it works like a charm!

Great job @JessicaJHee !

**Comment by angelozerr** [comment]
Thanks @JessicaJHee !

**Pull request merged**
