### PR TITLE
fix(build): set project encoding

### PR DESCRIPTION
**Pull request by rbioteau**
avoid platform specific encoding issues when building the project

### CODE REVIEW

**Comment by mickaelistria** [comment]
Thanks! Can you please amend your commit to add a `Signed-Off-By` footer and then push --force to replace this one on your branch? `git commit --amend --signoff` is usually enough.

**Comment by rbioteau** [comment]
Done, but the ECA check is still not happy :thinking:

**Comment by mickaelistria** [comment]
Have you signed the ECA?

**Comment by rbioteau** [comment]
Yes...

**Comment by mickaelistria** [comment]
The check says "Could not validate the users ECA sign-off status. Please ensure that the e-mail address of all contributing accounts match a valid Eclipse Foundation account with a valid ECA.".
Please send a mail to emo@eclipse-foundation.org to get assistance if you don't have any idea what could be wrong here.

**Comment by waynebeaton** [comment]
I've responded to Romain by private email.

For reference, the Author email address on the commit is different from the one used on the EF account and the Signed-off-by. The Author field on the commit needs to match what we have in your EF account, and the Signed-off-by value.

**Comment by mickaelistria** [comment]
Thank you @rbioteau !

**Pull request merged**
