### PR TITLE
launch for vscode debugging

### PR DESCRIPTION
**Pull request by angelozerr**
launch for vscode debugging

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
This PR provides a vscode launch for debugging lemminx-maven inside vscode.

See https://github.com/redhat-developer/vscode-xml/blob/master/docs/Extensions.md#debugging-your-java-lemminx-extension for more explanation

**Comment by mickaelistria** [comment]
Shouldn't that be part of vscode-xml instead?

**Comment by angelozerr** [comment]
> Shouldn't that be part of vscode-xml instead?

The idea is that you import lemminx-maven in vscode, and you can debug it. We have a similar file in lemminx https://github.com/eclipse/lemminx/tree/master/.vscode

**Comment by mickaelistria** [comment]
Why is that necessary for VSCode while this kind of thing is not necessary for other IDEs?

**Comment by angelozerr** [comment]
It's just a launch (like an Eclipse IDE launch) which is proper configured.

**Comment by mickaelistria** [comment]
Yes, but debugging Maven projects in Eclipse IDE usually work well without adding an Eclipse .launch file, and same for NetBeans and IntelliJ, I don't get what's so different with VSCode that makes it useful.

**Comment by angelozerr** [comment]
> Yes, but debugging Maven projects in Eclipse IDE usually work well without adding an Eclipse .launch file, and same for NetBeans and IntelliJ, I don't get what's so different with VSCode that makes it useful.

In Eclipse IDE, you have an UI which creates the launch, in vscode you have not that and you must write at hand the launch. This PR avoid writting at hand this file. You import the lemminx-maven in vscode and you benefit from this launch without writing at hand.

**Comment by mickaelistria** [comment]
> in vscode you have not that and you must write at hand the launch. 

OK, I thought there were some command in VSCode-Java to generate that kind of things.
I'll merge it because it doesn't harm and it makes you and others more productive; but I'm surprised that people have asked other IDEs a lot of effort to not require to check-in IDE-specific files in the project yet remain productive, and all of a sudden, committing another-IDE-specific file become almost necessary... Is this innovation or regression?

**Pull request merged**
