### PR TITLE
Completion should also propose other packaging types available in Bui…

### PR DESCRIPTION
**Pull request by vrubezhny**
…ld extensions #267

### CODE REVIEW

**Comment by mickaelistria** [comment]
One great test you could add would be to add a pom that defines Tycho as build extension plugin and check whether the `eclipse-plugin` type is available in completion.
I don't think it's so interesting to list other non-native packaging types if those can be inferred dynamically.

**Comment by vrubezhny** [comment]
Yes, I'm thinking on the test. Problem could be that MavenProject is only partially setup (because of `org.apache.maven.project.DefaultProjectBuilder` that isn't tolerant when parsing an incomplete document, thus not returning any result in case of packaging element is empty (throwing an `IllegalArgumentException` immediately after `ModelBuildingException` related to the empty packaging occurs - that's why I disabled the dependencies resolution on building the maven project). 
So a better test is needed for non-native packaging types.

**Comment by vrubezhny** [comment]
`MavenCompletionParticipantTest.testPackagingyCompletion` is added with the detection of `eclipse-plugin` packaging type defined in `org.eclipse.tycho:tycho-maven-plugin:2.7.5`

**Review by mickaelistria — APPROVED** [review]
Great addition!

**Pull request merged**
