### PR TITLE
Hover Participant - Cancel any operation as soon as possible.

### PR DESCRIPTION
**Pull request by vrubezhny**
Issue: #358

### CODE REVIEW

**Comment by angelozerr** [comment]
I'm glad @vrubezhny that you use this cancel support, but have you checked it is working with LSP4E?

I know that @mickaelistria has done something about this cancel support on LSP client side for hover, but it could be nice to check it is working with LSP4E by debugging the lemminx maven extension.

**Comment by vrubezhny** [comment]
@angelozerr Thanks for the info. 
The JUnit tests pass well, so the cancellation support  doesn't bring any visible problems. but I'll try finding out what @mickaelistria has  done on LSP client side and try debugging the extension.

**Comment by mickaelistria** [comment]
Cancellation is not yet supported in LSP4E, it got better but not yet complete. So at the moment, there is not even 1 client of lemminx-maven that supports cancellation, I suggest we just ignore it for the moment, until we can benefit from it on client side.

**Comment by angelozerr** [comment]
Vscode support cancel support

**Comment by mickaelistria** [comment]
> Vscode support cancel support

As far as I know, lemminx-maven is not yet supported in VSCode, is it?

**Comment by vrubezhny** [comment]
Once the cancellation is not fully supported in LSP4E, I can suggest a simple tests on LemMinX-Maven side, like handling an immediate cancellation that mostly check that the cancelling itself doesn't bring any problems. 
Later we can probably add some more testing.

**Comment by mickaelistria** [comment]
Automated test would be great!

**Pull request merged**
