### PR TITLE
Rename base package to org.eclipse.lemminx.extensions.maven

### LINKED ISSUE #121: Rename package base to org.eclipse.lemminx.extensions.maven
All LemMinx support like XSD, DTD are extensions and are stored in the [org.eclipse.lemminx.extensions](https://github.com/eclipse/lemminx/tree/master/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions) packages.

IMHO to be consistent with those extension, I suggest that you use `org.eclipse.lemminx.extensions.mave,` package as base package.

Similar issue than https://github.com/Treehopper/liquibase-lsp/issues/14

### PR DESCRIPTION
**Pull request by AObuchow**
Fix #121

Signed-off-by: Andrew Obuchowicz <andrew@aobuchow.com>

### CODE REVIEW

**Comment by AObuchow** [comment]
This might be a bit trickier than I thought, will have to inspect where the rename refactor introduced a bug.

**Comment by mickaelistria** [comment]
I think you forgot to modify lemminx-maven/lemminx-maven/src/main/resources/META-INF/services/org.eclipse.lemminx.services.extensions.IXMLExtension

**Comment by AObuchow** [comment]
> I think you forgot to modify lemminx-maven/lemminx-maven/src/main/resources/META-INF/services/org.eclipse.lemminx.services.extensions.IXMLExtension

That's right, thank you !

**Comment by mickaelistria** [comment]
Thanks @AObuchow !

**Pull request merged**
