### PR TITLE
Generate zip including runtime dependencies

### PR DESCRIPTION
**Pull request by fbricon**
See [vscode-xml-maven.zip](https://bit.ly/vsx-xml-maven), a rebuild of https://github.com/angelozerr/vscode-xml-maven.
Requires https://github.com/eclipse/lemminx/pull/873

### CODE REVIEW

**Comment by mickaelistria** [comment]
I'm waiting for linux CI to validate it before we merge, but the CI seems stuck by some other lemminx job. Can you please have a look?

**Comment by mickaelistria** [comment]
All CI tests passed, let's merge. Thanks @fbricon !

**Comment by angelozerr** [comment]
Is this zip can be downloaded in https://repo.eclipse.org/content/repositories/lemminx-snapshots/ for instance?

**Comment by mickaelistria** [comment]
> Is this zip can be downloaded in https://repo.eclipse.org/content/repositories/lemminx-snapshots/ for instance?

It's supposed to, but it looks like most recent builds did fail at properly building https://ci.eclipse.org/lemminx/job/LemMinX-Maven/job/master/93/

**Comment by angelozerr** [comment]
Just to explain why I need it, we are providing a new settings in vscode-xml to load LemMinx extension (to avoid developing custom vscode extension). We would like to explain in our documentation this settings and give a sample with LemMinx maven. That's why we need this URL zip.

> It's supposed to, but it looks like most recent builds did fail at properly building https://ci.eclipse.org/lemminx/job/LemMinX-Maven/job/master/93/

Is there any chance that you fix it soon?

**Comment by mickaelistria** [comment]
> Is there any chance that you fix it soon?

My backlog is currently full of items that are higher priority to me. Maybe next week.
In the meantime, if anyone else is willing to investigate, that would be welcome!

**Comment by angelozerr** [comment]
I don't understand the error:

```
[INFO] Building zip: /home/jenkins/agent/workspace/LemMinX-Maven_master/lemminx-maven/target/lemminx-maven-0.2.0-SNAPSHOT-zip-with-dependencies.zip
Killed
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 137
Finished: FAILURE
```

@fbricon have you some idea?

**Comment by mickaelistria** [comment]
this looks like an external process did kill the launch. Could it be that building the zip consumes too much RAM, more than allowed on the current agent?

**Pull request merged**
